name: fast-forward

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fast-forward merge main branch
        run: |
          git branch
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
