name: fast-forward

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fast-forward merge
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} -n
          git merge origin/${{ github.event.pull_request.base.ref }} -m "merge: \`${{ github.event.pull_request.base.ref }}\`" --ff && git push
