name: fast-forward

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fast-forward merge
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git fetch origin develop -n --unshallow
          git checkout develop
          git merge main -m "merge: \`main\`" --ff && git push
