name: fast-forward-merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fast-forward-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Create App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.AUTO_SYNC_BRANCH_CLIENT_ID }}
          private-key: ${{ secrets.AUTO_SYNC_BRANCH_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: app-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Fast-forward merge
        run: |
          git config user.name "${{ steps.app-token.outputs.app-slug }}[bot]"
          git config user.email "${{ steps.app-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git fetch origin develop -n --unshallow
          git checkout develop
          git merge main -m "merge: \`main\`" --ff && git push
