name: fast-forward

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fast-forward merge main branch
        run: |
          git fetch origin main -n
          git merge origin/main --ff-only && git push
