name: fast-forward

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fast-forward merge
        run: |
          git fetch origin
          git branch --all
          git checkout develop
          git merge main -m "merge: \`${{ github.event.pull_request.base.ref }}\`" --ff && git push
