name: fast-forward

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fast-forward merge main branch
        run: |
          git branch
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
