name: fast-forward

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fast-forward merge
        run: |
          git fetch origin develop -n --unshallow
          git checkout develop
          git merge main -m "merge: \`${{ github.event.pull_request.base.ref }}\`" --ff && git push
